apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment2048
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment2048
  template:
    metadata:
      labels:
        app: deployment2048
    spec:
      containers:
      - name: 2048-container
        image: erenduyuk/2048-image:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: service2048
spec:
  selector:
    app: deployment2048
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort